
platform :ios, '16.0'

source 'https://cdn.cocoapods.org/'

require_relative '../../my-new-rnapp/node_modules/react-native/scripts/react_native_pods'
# 仅注册 use_react_native! 缺失的关键 podspecs
pod 'fast_float', :podspec => '../../my-new-rnapp/node_modules/react-native/third-party-podspecs/fast_float.podspec'

target 'ReactNativeFramework_Example' do
  use_frameworks!
  
  use_react_native!(
    :app_path => "../../my-new-rnapp",
    :path => "../../my-new-rnapp/node_modules/react-native",
    :production => false,
    :hermes_enabled => true,
    :fabric_enabled => true,
  )

  pod 'ReactNativeFramework', :path => '../'

  target 'ReactNativeFramework_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    "../../my-new-rnapp/node_modules/react-native",
    :mac_catalyst_enabled => false,
  )
  
  # 解决重复 UUID 问题
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
       config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
       
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
       config.build_settings['AD_HOC_CODE_SIGNING_ALLOWED'] = 'YES'
       config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
      
      # 🔥 关键：禁用新的签名格式
       config.build_settings['OTHER_CODE_SIGN_FLAGS'] = '$(inherited) --signature-version 1'
     end
   end

  installer.pods_project.targets.each do |target|
    target.build_phases.each do |phase|
      if phase.respond_to?(:shell_script) && phase.shell_script
        phase.shell_script = phase.shell_script.gsub('../../node_modules/', '../../my-new-rnapp/node_modules/')
        phase.shell_script = phase.shell_script.gsub('${PODS_ROOT}/../../node_modules', '../../my-new-rnapp/node_modules')
        phase.shell_script = phase.shell_script.gsub('$PODS_ROOT/../../node_modules', '../../my-new-rnapp/node_modules')
      end
    end
  end
  
  # 🔥 识别所有 React Native 相关 Pod
  installer.pods_project.targets.each do |target|
    # 方法1: 包含特定前缀
    is_react_pod = target.name.start_with?('React-', 'RCT', 'FBLazyVector', 'FBReactNativeSpec')
    
    # 方法2: 或者使用正则
    is_react_pod ||= target.name.match?(/^(React|RCT|FBLazyVector|FBReactNativeSpec)/)
    
    # 方法3: 排除可能误匹配的
    is_react_pod &&= !target.name.start_with?('ReactNativeFramework')
    
    if is_react_pod
      target.build_configurations.each do |config|
        config.build_settings['MACH_O_TYPE'] = 'staticlib'
        config.build_settings['DEFINES_MODULE'] = 'NO'
        config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = '$(inherited)'
      end
    end
  end
  
end
